name: CI with Prettier
on:
  push:
    branches: ["**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
      - name: Install Prettier
        run: npm i -g prettier
      - name: Ensure formatting with Prettier
        run: prettier -c .
